name: Build and Upload Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio

      - name: Build firmware
        run: pio run

      - name: Upload .pio/build/pico/firmware.uf2
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: .pio/build/pico/firmware.uf2