name: Build and Upload Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up PlatformIO
      uses: platformio/action-setup@v2
      with:
        platform: ${{ matrix.platform }}
        board: ${{ matrix.board }}

    - name: Build firmware
      run: pio run

    - name: Upload firmware as artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: .pio/build/${{ matrix.platform }}/firmware.bin
